/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
      extend: {
          colors: {
              "surface-dim": "#d3daea",
              "on-error-container": "#93000a",
              "secondary": "#58579b",
              "outline": "#777587",
              "inverse-on-surface": "#ebf1ff",
              "primary-fixed-dim": "#c3c0ff",
              "on-tertiary-fixed": "#351000",
              "tertiary-container": "#a44100",
              "on-surface": "#151c27",
              "on-tertiary-container": "#ffd2be",
              "on-secondary-fixed": "#140f54",
              "on-background": "#151c27",
              "on-tertiary-fixed-variant": "#7b2f00",
              "secondary-fixed": "#e2dfff",
              "tertiary-fixed-dim": "#ffb695",
              "surface-container-highest": "#dce2f3",
              "inverse-surface": "#2a313d",
              "on-primary-fixed": "#0f0069",
              "surface": "#f9f9ff",
              "error": "#ba1a1a",
              "tertiary": "#7e3000",
              "on-primary": "#ffffff",
              "primary": "#3525cd",
              "inverse-primary": "#c3c0ff",
              "surface-container": "#e7eefe",
              "on-primary-container": "#dad7ff",
              "surface-container-low": "#f0f3ff",
              "on-secondary": "#ffffff",
              "background": "#f9f9ff",
              "on-secondary-container": "#454386",
              "on-error": "#ffffff",
              "surface-container-lowest": "#ffffff",
              "surface-bright": "#f9f9ff",
              "tertiary-fixed": "#ffdbcc",
              "secondary-container": "#b6b4ff",
              "on-tertiary": "#ffffff",
              "surface-container-high": "#e2e8f8",
              "secondary-fixed-dim": "#c3c0ff",
              "on-surface-variant": "#464555",
              "surface-variant": "#dce2f3",
              "error-container": "#ffdad6",
              "on-secondary-fixed-variant": "#413f82",
              "on-primary-fixed-variant": "#3323cc",
              "surface-tint": "#4d44e3",
              "outline-variant": "#c7c4d8",
              "primary-container": "#4f46e5",
              "primary-fixed": "#e2dfff"
          },
          fontFamily: {
              "headline": ["Inter", "sans-serif"],
              "body": ["Inter", "sans-serif"],
              "label": ["Inter", "sans-serif"]
          },
          borderRadius: {"DEFAULT": "0.25rem", "lg": "1rem", "xl": "1.25rem", "full": "9999px"},
      },
  },
  plugins: [],
}
