apiVersion: v1
kind: Service
metadata:
  name: hashguard-backend-service
spec:
  selector:
    app: hashguard-backend
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: hashguard-frontend-service
spec:
  selector:
    app: hashguard-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
